spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
