spring:
  datasource:
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_URL}
    host: ${HOST}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: ${PORT}
